dingtalk:
  id: 10435002
  key: suitegqebx814dt8immqw
  corpId: dingc7c5220402493357f2c783f7214b6d69
  secret: AXjjwYhZ7Bwh1e8vlkg7pPQHUACwl8rSJWFma1taYMDLUjmIAtl9d9yAdTBg4K3m
  corpSecret: 39dtrDv5hqnRc9k6Qb49NFypuAqinCRfyS0YiyHKzdEmRKCeoo_ASpwsvjN47mrp
  isv: true
  apis:
    - runtime.info
    - biz.contact.choose
    - device.notification.confirm
    - device.notification.alert
    - device.notification.prompt
    - biz.ding.post
    - biz.util.openLink
  token: 123456
  aes: 7fydkdigg2jzcs7hshc49uoukemhp1tnxx604j4qv9p
server:
  port: 8100