dingtalk:
  id: 1279842668
  key: dingsoxqy0cobtzqmxud
  secret: rqKkOr54z2iwVnV8Y0tT1TYua0hPEX78PdytG-cP6JKj7m-V3A3zKt8xQZt3B5Oy
  isv: false
  apis:
    - runtime.info
    - biz.contact.choose
    - device.notification.confirm
    - device.notification.alert
    - device.notification.prompt
    - biz.ding.post
    - biz.util.openLink
