dingtalk:
  id: 1279813775
  key: dinggcd3ej0tk8qgktoq
  secret: 1kwSXdjyg3Alrh7lWNzYAHTX5Np8eRyqezvobeT9faFeOdyPoNqXWb3sxd3gPTPz
  isv: false
  apis:
    - runtime.info
    - biz.contact.choose
    - device.notification.confirm
    - device.notification.alert
    - device.notification.prompt
    - biz.ding.post
    - biz.util.openLink
