dingtalk:
  id: 10435002
  key: suitegqebx814dt8immqw
  corpId: dinggcd3ej0tk8qgktoq
  secret: AXjjwYhZ7Bwh1e8vlkg7pPQHUACwl8rSJWFma1taYMDLUjmIAtl9d9yAdTBg4K3m
  corpSecret: 39dtrDv5hqnRc9k6Qb49NFypuAqinCRfyS0YiyHKzdEmRKCeoo_ASpwsvjN47mrp
  isv: false
  apis:
    - runtime.info
    - biz.contact.choose
    - device.notification.confirm
    - device.notification.alert
    - device.notification.prompt
    - biz.ding.post
    - biz.util.openLink
  token: test
  aes: c3s85esplcaiecruses5rgrxznp6bho87lwbgbrb1zq
